# Generated by Django 5.0.3 on 2024-04-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palmirinha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tempo_de_preparo',
            field=models.TimeField(blank=True, max_length=4, null=True),
        ),
    ]
