# Generated by Django 5.0.3 on 2024-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palmirinha_app', '0002_receita_tempo_de_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='URL',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='creditos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='fonte',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_de_preparo',
            field=models.TimeField(help_text='Horas:Minutos', max_length=4, null=True),
        ),
    ]
